[package]
name = "Hunter"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
colored = "2.1"

[profile.release]
opt-level = "z"
strip = true
debug = false
